version: '3'

# docker pull selenoid/vnc:chrome_73.0
# docker pull selenoid/video-recorder:latest-release

# docker volume create selenoid-videos

# docker network create selenoid
# docker network rm selenoid
networks:
  default:
    external:
      name: selenoid

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - .:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/project/protractor_v6_mocha_ts_seed/video:/opt/selenoid/video
      - ./logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/project/protractor_v6_mocha_ts_seed/video
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-limit", "2",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-container-network", "selenoid"
    ]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: --selenoid-uri http://selenoid:4444
