version: '3'

networks:
  default:
    external:
      name: selenoid

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - .:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
#     if linux then:
#     - ./artifacts/video:/opt/selenoid/video
#     if Windows then:
      - /c/project/protractor_v6_mocha_ts_seed/artifacts/video:/opt/selenoid/video
      - ./artifacts/logs:/opt/selenoid/logs
    environment:
#     if linux then:
#     - OVERRIDE_VIDEO_OUTPUT_DIR=/artifacts/video
#     if Windows then:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/project/protractor_v6_mocha_ts_seed/artifacts/video
    command: [
      "-conf", "/etc/selenoid/browsers.conf.json",
      "-limit", "3",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-container-network", "selenoid"
    ]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: --selenoid-uri http://selenoid:4444
